### ISSUE TITLE
Need the ability to create a shopcart

### ISSUE THREAD

**Issue by nonococoleo** [NYU-DevOps2020-shopcarts/shopcarts#1]
**As a** eCommerce website user
**I need** the shop cart creation service to create my own shop cart.
**So that** I could add a collection of products that I am going to buy 

**Assumptions:** 
* a shop cart table is needed in the database
* query shopcarts by user inforamtion
* if a user doesn't have a shop cart, then create a shop cart record and associate with user

**Acceptance Criteria:**
```
Given that the user doesn't have a shop cart
When I put a POST request on '/shopcarts'
Then a shop cart record will be created in the table with the corresponding customer information, 
in which Unique ID of the newly created shop cart should be automatically generated as primary key.
The status code "201 Created" will be returned, including the description the status of the request 
and ID of the new shop cart, and a Location header
```

**Comment by KHafner** [comment]
Acceptance criteria item "The status code "201 Created" will be returned, including the description the status of the request and ID of the new shop cart, and a Location header" will instead be handled in #36
