### ISSUE TITLE
Delete shopcart

### ISSUE THREAD

**Issue by gauridhawan** [NYU-DevOps2020-shopcarts/shopcarts#10]
**As a** customer   
**I need** the ability to completely remove a shopcart  
**So that** I can remove a shopcart that I don't want to order 

**Assumptions:** 
* The customer is authorized to perform this action 

**Acceptance Criteria:**
```
Given the user id
When a customer makes a DELETE request to '/shopcarts' 
Then the shopcart is made inactive  and should return a 201 back to the user with an appropriate message
```

**Comment by jules203** [comment]
Make an edit for "delete" to mean delete the shopcart itself, rather than the items. i.e. if a customer leaves the platform, they no longer will have a shopcart.
