### ISSUE TITLE
List shopcart

### ISSUE THREAD

**Issue by gauridhawan** [NYU-DevOps2020-shopcarts/shopcarts#11]
**As an** admin 
**I need** to list all the shopcarts present in the system
**So that** I can see all the available shop carts  

**Assumptions:** 
* There exists a shopcart database
* User is authorized to perform this action

**Acceptance Criteria:**
```
Given an authorized admin user
When the user makes a GET request to '/shopcarts' 
Then the response should contain all active shopcarts in the database
```

**Comment by jules203** [comment]
Ask professor and/or delete because it is repetitive

**Comment by nonococoleo** [comment]
list should be for admin?
