### ISSUE TITLE
Send Order to Order App

### ISSUE THREAD

**Issue by iLtc** [NYU-DevOps2020-shopcarts/shopcarts#115]
**As a** customer
**I need** to place an order
**So that** I can finish my shopping experience 

**Assumptions:** 
* When the user places an order, we will send the order to the order team.

**Acceptance Criteria:**
```
Given the user has a shopcart and has put some items in the shopcart
When the user places an order
Then we will send the order to the order team
```

**Comment by iLtc** [comment]
Question: for TDD and BDD tests, do we need to verify that the order has been sent correctly to the order team?

**Comment by KHafner** [comment]
> Question: for TDD and BDD tests, do we need to verify that the order has been sent correctly to the order team?

I think we can use MagicMock for TDD
