### ISSUE TITLE
Create test cases

### ISSUE THREAD

**Issue by KHafner** [NYU-DevOps2020-shopcarts/shopcarts#17]
**As a** Developer
**I need** to be able to easily test the service and model 
**So that** I can quickly identify bugs to work on 

**Assumptions:** 
* Test cases are located in the ./tests folder
* There should be test cases for Create, Read, Update, Delete, List, Query, traversing both happy paths and sad paths
* Need to add a test_service.py containing the test cases for the service
* Need to add a test_models.py containing the test cases for the model

**Acceptance Criteria:**
```
Given the fact that we are using nosetest
When I run nosetest
Then I will run these created test cases. The coverage needs to be over 95% for the tests to be considered successful.
```

**Comment by jules203** [comment]
More specific assumptions - about test and update

**Comment by jules203** [comment]
One API - one person testing

**Comment by iLtc** [comment]
I created a PR template to remind everyone to update documentation and test cases.
