### ISSUE TITLE
add query & modify functions in model

### ISSUE THREAD

**Issue by nonococoleo** [NYU-DevOps2020-shopcarts/shopcarts#33]
**As a**  developer
**I need** query & modify functions in model
**So that** search for records I need

**Assumptions:** 
* functions to query in db needs to be implemented

**Acceptance Criteria:**
```
When call query function in model
Then i get target records from db
When call modify function in model
Then i modify target records in db
```

**Comment by iLtc** [comment]
I think the professor said whoever works on a specific API (create, read, update, delete) should also write the function for the model.

So do we really need a separate issue for functions?

**Comment by nonococoleo** [comment]
> I think the professor said whoever works on a specific API (create, read, update, delete) should also write the function for the model.
> 
> So do we really need a separate issue for functions?

OKay, I might have missed what he said. In that case, this story is unnecessary. close it.
