### ISSUE TITLE
Refactor to use Flask-RESTPlus

### ISSUE THREAD

**Issue by KHafner** [NYU-DevOps2020-shopcarts/shopcarts#45]
**As a** developer
**I need** to refactor this micro service to use Flask-RESTPlus
**So that** I can easily add Swagger documentation

**Assumptions:** 
* Need to add `flask-restplus==0.13.0` to requirements.txt
* File layout should be changed from`/shopcarts` to `/api/shopcarts`

**Acceptance Criteria:**
```
When I run nosetests
Then all tests still pass.
```

**Comment by iLtc** [comment]
I will close this one since I have split it into smaller stories.
