### ISSUE TITLE
Test model services

### ISSUE THREAD

**Issue by jules203** [NYU-DevOps2020-shopcarts/shopcarts#5]
**As a** Tester
**I need** to test the model
**So that** we are able to identify any weaknesses in the service

**Assumptions:** 

- The goal of testing is to minimize risk and prevent issues
- WIth testing we evaluate the functionality of a software or system
- We will need to separately test the different portions of Shopcart; Create, Update, View, Delete, etc.
- Testing relates to the quality assurance stage of software development and deployment

**Acceptance Criteria:**
```
Given the specifications for what Shopcart should enable users to do
When the model allows users to read, update, delete, list out, query, and perform actions on resources in Shopcart
Then we can accept the system.
```

**Comment by jules203** [comment]
EDIT Assumptions section

**Comment by nonococoleo** [comment]
I think the assumptions part should focus on how to resolve this issue, the current content could be put into Acceptance Criteria

**Comment by jules203** [comment]
testing should be more specific - one for update, one for view, etc. create etc
