### ISSUE TITLE
Create a Python Flask Cloud Foundry application in IBM Cloud

### ISSUE THREAD

**Issue by iLtc** [NYU-DevOps2020-shopcarts/shopcarts#67]
**As a** developer
**I need** to have an application in IBM Cloud
**So that** I can deploy the app to the cloud

**Assumptions:** 
* Create a Python Flask Cloud Foundry application in IBM Cloud - US South
* The application name is `nyu-shopcart-service-f20`
* The full URL will be `nyu-shopcart-service-f20.us-south.cf.appdomain.cloud`

**Acceptance Criteria:**
```
When I visit my IBM cloud account
Then I can see the application
```

**Comment by nonococoleo** [comment]
python Cloud Foundry app has been created on ibm cloud, which can be accessed via URL: https://nyu-shopcart-service-f20.us-south.cf.appdomain.cloud/
