### ISSUE TITLE
Add a Unit Test Job to the Build Stage of the pipeline

### ISSUE THREAD

**Issue by iLtc** [NYU-DevOps2020-shopcarts/shopcarts#72]
**As a** developer
**I need** to set up TDD unit tests
**So that** I can deploy my service to the IBM cloud automatically

**Assumptions:** 
* Need to add a Build Stage to the Pipeline
* Need to add a unit Test Job in the Build Stage of the pipeline to be used to run units tests with nosetests

**Acceptance Criteria:**
```
Given that the Build stage will run TDD unit tests
When Pull Requests run unit tests and no pull request gets merged that will break the master branch
Then we will know that the pipeline is operational.
```

**Comment by KHafner** [comment]
Assigned to myself, I had to do this step as the repo owner so the webhook could be created
