### ISSUE TITLE
Add a Dev Deployment Stage to the pipeline

### ISSUE THREAD

**Issue by iLtc** [NYU-DevOps2020-shopcarts/shopcarts#73]
**As a** developer
**I need** to set up TDD unit tests
**So that** I can deploy my service to the IBM cloud automatically

**Assumptions:** 
* A Unit Test Job in the Build Stage of the pipeline is used to run units tests with nosetests
* Need to add Dev Deployment Stage to the pipeline to deploy to the Dev space if the unit tests pass

**Acceptance Criteria:**
```
Given that the Build stage will run TDD unit tests
When Pull Requests run unit tests and no pull request gets merged that will break the master branch
Then we will know that the pipeline is operational.
```

**Comment by KHafner** [comment]
Added a fix to change to application name from nyu-shopcart-service to nyu-shopcart-service-f20
