### ISSUE TITLE
Update shopcart

### ISSUE THREAD

**Issue by gauridhawan** [NYU-DevOps2020-shopcarts/shopcarts#8]
**As a** customer   
**I need** to update items in my shopcart
**So that** I can modify the entries in my shopcart

**Assumptions:** 
* The user should be a valid user have permissions to add to that particular shopcart
* Items in the shopcart cannot be in negative 
* The item being updated is already present 

**Acceptance Criteria:**
```
Given the shopcart id and item id
When an authorized user hits a PATCH/PUT request on '/shopcarts'
Then the API will return the updated shopcart with a status code 200
```

**Comment by iLtc** [comment]
If the cart does not exist, call the create API to create a new one.

**Comment by nonococoleo** [comment]
> If the cart does not exist, call the create API to create a new one.

API should just do one thing? just return "shopcart doesn't exist"
